stages:
  - tests

php_unit:
  stage: tests
  image: composer:2
  cache:
    paths:
      - .composer-cache/
  before_script:
    - PATH=$(composer global config bin-dir --absolute --quiet):$PATH
    - composer config -g cache-dir "$(pwd)/.composer-cache"
  script:
    - composer install --quiet
    - ./vendor/bin/codecept run unit
  when:
    - manual
